### ISSUE TITLE
Automatically check that translations are "well-formed"

### ISSUE THREAD

**Issue by viroulep** [thewca/wca-regulations-translations#27]
I believe @Claster has been doing this by hand for the French and German translation, we should automate that !
I'll try to somehow add a pass during the Regulations' translation build process, that would check that translated Regulations and Guidelines number exactly match the original Regulations and Guidelines.

Do you see anything nice that could be added while I'm at it ?

**Comment by Claster** [comment]
Surely I didn't do it by hand! I wrote a script.
That script checked that:
1) After "table-of-contents" every line has the first non-space symbol '-' or '#' (expection: beginning of Z-article).
2) Indentation in regulations is correct, in guidelines is absent;
3) In guidelines every line has a label in brackets, and there are 6 different labels;
4) Set of regulation numbers in translation matches the set of regulation numbers in English version.

**Comment by viroulep** [comment]
Ahah nice :D
Could you add it to the build process yourself? or give me the code so that I could add it?

**Comment by Claster** [comment]
Well, that's not a "best practices" code.

https://gist.github.com/Claster/2a30cc40057ab1fe1e63525584de27dc

Where can I find a build process btw? I could look into adding it tomorrow evening.

**Comment by Laura-O** [comment]
Nice idea! :-)

We should also check for invalid links, especially the old link to the contact page: [https://www.worldcubeassociation.org/contact-information](https://www.worldcubeassociation.org/contact-information)
Maybe just for any 404 links?

**Comment by viroulep** [comment]
@Claster the directory with build scripts is in the website repository, right [there](https://github.com/cubing/worldcubeassociation.org/blob/master/regulations).

I'd suggest implementing this in [html.py](), where I already did some stuff to detect guidelines with missing regulations (you can probably reuse the [`regulations_set`](https://github.com/cubing/worldcubeassociation.org/blob/master/regulations/html.py#L34) I used).

IIRC, you don't have to build the full website to be able to build the regulations. After you initialized the translations submodule, if you have all the needed [dependencies](https://github.com/cubing/worldcubeassociation.org/blob/master/regulations/README.md#dependencies) you can just go to the `regulations` directory and run:
```
./make.py --num-workers=1 --no-pdf --all
```
The no-pdf option will enable you to pass on installing the huge texlive stuff needed to build the pdfs.

**Comment by lgarron** [comment]
Also note that `html.py` is currently pretty terrible. I chose to use regexes in Python because it seemed like it would be the most maintainable for novice programmers. It's worked pretty well so far, but it won't scale.

A better choice would be to use Haskell with `pandoc` to work on the `AST`, or at least use [BeautifulSoup](http://www.crummy.com/software/BeautifulSoup/bs4/) in Python.

**Comment by Claster** [comment]
Hmm, I don't think it is a good idea to put checks into html.py. I'd rather create a separate script for that. WDYT?

**Comment by viroulep** [comment]
Right ! You could create an external module and call it from [make.py](https://github.com/cubing/worldcubeassociation.org/blob/master/regulations/make.py#L199).

**Comment by viroulep** [comment]
this is actually fixed with all the travis things we added :)
(#35)
