### ISSUE TITLE
Readme.md broken link

### ISSUE THREAD

**Issue by DesWurstes** [thewca/wca-regulations-translations#50]
> Read through the **[style guide](https://github.com/cubing/wca-documents-extra/blob/master/style-guide.md)** for detailed information about how the Regulations are formatted.

^Link broken.

**Comment by Laura-O** [comment]
Thanks, fixed!

**Comment by jfly** [comment]
@Laura-O, it's nice if you include a comment like "fixes #50" in your commits, which will automatically close issues like this, and provide a papertrail so other people watching can see how these issues were fixed.

For everyone else watching, @Laura-O addressed this issue in 4b1451a03bab246c1b92f85f54157d0dcdb37341.

**Comment by Laura-O** [comment]
Yes, you are right. Just completely forgot to do that.
So thanks for linking the commit.
