### ISSUE TITLE
Write correct version of Russian translation

### ISSUE THREAD

**Issue by AlexKatyukov** [thewca/wca-regulations-translations#76]
Now we have Russian translation for 2019-05-01 version, but in list of translation marked that the translation is for 2018.
![Screenshot](https://user-images.githubusercontent.com/18090165/63964091-08eef680-ca9f-11e9-92c1-723ffb9e8ff7.png)

**Comment by viroulep** [comment]
Fixed in thewca/worldcubeassociation.org#4622

**Comment by hanwu85** [comment]
Thanks!  Issue fixed. Close this now.
